### ISSUE TITLE
Add a `bend_pitch` function

### ISSUE THREAD

**Issue by pitag-ha** [pitag-ha/cardio-crumble#9]
Currently, the only MIDI voice messages we manage are `note on` and `note off`. It would be interesting for `cardio-crumble` to have a richer pool of messages to choose from. I suggest adding another voice message to the `Midi` module. You can have a look at [this summary of midi channel voice messages](https://cmtext.indiana.edu/MIDI/chapter3_channel_voice_messages.php) for ideas and specifications.

One idea would be to add a `bend_pitch` function sending a `Pitch Bend` message. The signature could look as follows:
```
val bend_pitch : bend:char -> timestamp:int32 -> Event.t
```
where `bend` represents the pitch bend one wants to send in 14-bit resolution.

This issue is only about adding this new function to the `Midi` module (as a first step). In another issue later, we can use such a function.

**Comment by kamtoeddy** [comment]
Hi @pitag-ha, I have already completed the setup. I also  compiled  and ran the MirageOS hello-world. Please can I work this issue?

**Comment by pitag-ha** [comment]
Sure, please go ahead, @kamtoeddy. Let us know if you have any question!

**Comment by kamtoeddy** [comment]
Hi @pitag-ha,

I need your help

This is what I have come up with:
```ocaml
let bend_pitch ~bend ~timestamp () =
  Event.create ~status:'\144' ~data1:bend ~timestamp
```

The inspiration was drawn from the `message_on` and `message_off` methods that have already been implemented in the `Midi` module

So far I have learned that `~` is used for named parameters in functions just like in python

I have a few doubts about my solution
- I am not sure the value of `status` I am passing to the port midi event is correct
- Looking into the documentation of the port midi, [here](https://github.com/mbacarella/portmidi/blob/main/portmidi.mli) I realised that Event.create expects 4 parameters `status:char`, `data1:char`, `data2:char` & `timestamp:int32` but in my solution I do not have a value to pass as `data2`

**Comment by pitag-ha** [comment]
Hi @kamtoeddy, great that you're already making progress! To find out which values to pass to `Event.create` as `data1` and `data2`, you can have a look at [this summary of the MIDI speficiations for channel voice messages](https://cmtext.indiana.edu/MIDI/chapter3_channel_voice_messages.php) to which I pointed in the issue. In particular, the following part of the table is what we're interested in:

Status Byte | Data Byte 1 | Data Byte 2 | Message | Legend
-- | -- | -- | -- | --
1110nnnn | 0fffffff | 0ccccccc | Pitch Bend | n=channel c=coarse f=fine (c+f = 14-bit resolution)
-- | -- | -- | -- | --

Do you know how to read that table? Or would you like me to explain it?

As a first step to figure out what to pass in as `data1` and `data2`, you can ask yourself the following questions:  In the range from where to where do you expect `bend` to be? In the range from where to where does `data1` have to be? And in the range from where to where does `data2` have to be?

**Comment by kamtoeddy** [comment]
Hi @pitag-ha, I have looked into the summary again and this time, with the help of your hints I understand this:
- `data1` and `data2` are represented in binary in 8 bits  (2<sup>8</sup> = [0, 127])
- `bend` is comprised of the 7 last bits of `data2` and `data1` in that order. Hence represented as 2<sup>14</sup> in binary

Does this mean I should do something like this?
```ocaml
let data1 = String.sub bend 7 7
let data2 = String.sub bend 0 7
```

**Comment by Engil** [comment]
`data1` and `data2` are both represented as `char` in our implementation.
A `char` in OCaml is an 8bit value.

You are right on how `bend` is represented, but your solution is not going to work as you are working with strings.

I can give you a few hints on how to work with this:

First, you can move values from `int` to `char` in OCaml using `Char.chr`. (the opposite operation is `Char.code`, to get a char from an int).

Knowing this you can now reason with `chars` as numbers rather than actual characters, which is what your are looking for.

Another interesting thing you can do to make your life easier, is that in OCaml, you are allowed to write integers in binary form (or hexadecimal!) using a prefix when writing your number.

For example, writing `let i = 0b10` is the same as writing `let i = 2`.

Let me know if you have more questions.

**Comment by kamtoeddy** [comment]
Thank you @Engil

**Comment by kamtoeddy** [comment]
@pitag-ha @Engil sorry I have not implemented anything yet even with all the info you've shared so far

Maybe the problem is the way I interpret the problem. So here is how I intend to solve the problem
- the `bend_pitch` function takes in `bend:char` & `timestamp:int32` represented using 14bits in binary
- convert `bend` to binary so as to extract `data1` & `data2`
- convert `data1` & `data2` from binary to chars
- pass char versions of  `data1` & `data2`, `status`, `timestamp`  to Event.create

The only progress so far is getting the value of the status to be `'\224'`  from the table above and comparing with the value of status of `message_on` & `message_off`

**Comment by Engil** [comment]
@kamtoeddy it is non trivial!

You will need to do some bitwise manipulation to implement it properly. 😊 

I can give you some pointers!

Let's first assume the bend pitch you want to build is `16383` (the maximum size 14 bits value in decimal, namely `0x11111111111111`.

You need to build `data1` and `data2` from it. One way to think about it is that you want to split this number in two (not unlike your `String.sub` proposal from earlier.).

How can one achieve this? Using [bitwise operations](https://en.wikipedia.org/wiki/Bitwise_operation)!

Let's say you want to extract the upper 7 bits of the integer we first described. For this, you could use a logical left shift operation to _shift_ seven bits to the left, removing the lower 7 bits.

To extract the lower 7 bits, you need to be using something else, however. You would need to use some kind of _mask_ to _hide_ the higher 7 bits so you are only left with the lower 7 bits.
This can be done using a logical `AND` bit operation.

For this one I can give you a simple example, given a value `0b1001` where we want to hide the upper two bits `10`, we can do something like this:
```
0b1001 land 0b0011
```

This would give us `1`, or `01`, namely the last two bits of `0b1001`. :-)

Let me know if you'd like more example or informations. Also, do note that OCaml is peculiar on naming the bitwise operators, you can find them in the Stdlib documentation here: https://v2.ocaml.org/api/Stdlib.html
(`lsl` is the name for the logical left shift operator!)

**Comment by AryanGodara** [comment]
This conversation was very useful in understanding about the repo. I had a great time going through this hehe!! 😁
